### ISSUE TITLE
Type of `delegate(Element, string, EventType, Handler)` doesn't seem to work

### ISSUE THREAD

**Issue by bfred-it** [bfred-it/delegate-it#6]
These work in TypeScript:

```js
delegate(".base", ".clickable", "click", handler);
delegate(select.all(".base"), ".clickable", "click", handler);
This doesn't
```

But the `Single base element specified` overload doesn't:

```js
delegate(select(".base"), ".clickable", "click", handler);
```

```
      TS2345: Argument of type 'HTMLElement | null' is not assignable to parameter of type 'string | ArrayLike<Element>'.
  Type 'null' is not assignable to type 'string | ArrayLike<Element>'.
```

cc @nickytonline

**Comment by nickytonline** [comment]
I'll take a peek at this tonight.

**Comment by nickytonline** [comment]
It looks like you need to make the `elements` parameter type `EventTarget | Document | Element` (or maybe `HTMLElement` as well or instead of `Element`) on this line, https://github.com/bfred-it/delegate-it/blob/master/index.ts#L118

**Comment by bfred-it** [comment]
D'oh. PR welcome to get the _blame_ 😅

**Comment by nickytonline** [comment]
Didn't have time last night to PR. I'll do it later tonight.

**Comment by bfred-it** [comment]
I think… that’s because select returns `HTMLElement | null`
I’ll try again with `select()!`

**Comment by bfred-it** [comment]
Indeed it was! Sorry about the noise 😅 

![](https://user-images.githubusercontent.com/1402241/57437476-70750200-7274-11e9-8e00-3491fa194d5b.gif)
