### ISSUE TITLE
Duplicate detection is broken when using options rather than the capture boolean

### ISSUE THREAD

**Issue by stof** [bfred-it/delegate-it#9]
The spec says that duplicate detection is based on callback, type and capture only. But your code does not properly implement that when passing an options object as last argument (you test for options objects being the same, which is much less likely).

https://dom.spec.whatwg.org/#add-an-event-listener

**Comment by stof** [comment]
I think this is because the duplicate detection was implemented at a time when the last argument was documented as `boolean`  only.

**Comment by bfred-it** [comment]
Excellent. I recently found a pattern to fix all this, actually. I'll work on it

**Comment by bfred-it** [comment]
https://github.com/bfred-it/delegate-it/pull/10
